#! /bin/bash
#
# Checks to see if data has been updated recently.
#
# Copyright 2006 Mozilla Foundation
# Author: Dave Miller <justdave@mozilla.com>

CONFIG_DIR=/etc/nagios/tinderbox-monitoring
CONFIG_FILE=$CONFIG_DIR/$1.txt

VER=
VERSION_URL=$(grep "VERSION_URL" "$CONFIG_FILE" | tail -n 1 | sed 's/.*VERSION_URL[[:space:]]*//')
SHIPPED_LOCALES_URL=$(grep "SHIPPED_LOCALES_URL" "$CONFIG_FILE" | tail -n 1 | sed 's/.*SHIPPED_LOCALES_URL[[:space:]]*//')

if [ ! -z $VERSION_URL ]; then
    VER=$(wget -q --timeout=7 -O- "$VERSION_URL" | grep -P '^\d\.\d.*' | tail -n 1)
    if [ -z $VER ]; then
        echo "Cannot parse version information"
        exit 1
    fi
fi

if [ ! -z $SHIPPED_LOCALES_URL ]; then
    LOCALES=$(wget -q --timeout=7 -O- "$SHIPPED_LOCALES_URL" | grep -vE '^(ja|en-US)')
    if [ -z "$LOCALES" ]; then
        echo "Cannot get locale information"
        exit 1
    fi
fi

output=$(grep -v ^# $CONFIG_FILE | tr -d '\r' | sed "s/@VER@/$VER/g"  | \
while read line; do
    if [[ "$line" =~ @LOCALE@ ]]; then
        for locale in $LOCALES; do
            $CONFIG_DIR/check_nightly_builds -a 100800 -f ${line/@LOCALE@/$locale}
        done
    else
        $CONFIG_DIR/check_nightly_builds -a 100800 -f $line
    fi

done | grep CRITICAL)

if [ ! -z "$output" ]; then
  echo $output | sed 's/CRITICAL: //g'
  exit 2
else
  echo "All tested files OK."
  exit 0
fi

